### ISSUE TITLE
Help & Fix (auto save text & fixed Display)

### ISSUE THREAD

**Issue by lolminerxmrig** [xzajyjs/ThunderSearch#19]
Hi.
plz help for auto save txt.

plz fixed Display
![image](https://github.com/xzajyjs/ThunderSearch/assets/108659226/373558c7-89f5-4ed2-aa28-e886e7dfa0d6)

My Config:

![image](https://github.com/xzajyjs/ThunderSearch/assets/108659226/20e65c58-1e12-41d2-98a2-f1fbb66ff4cf)

**Comment by xzajyjs** [comment]
plz change "SaveMode" from `不保存` to `存文件`  
On my windows, zoom looks normal. This bug is attributed to the scaling adaptation problem of Windows to high-resolution screens.

<img width="792" alt="pic-002642" src="https://github.com/xzajyjs/ThunderSearch/assets/25580455/867242d5-b2e2-4ab1-ba73-33011c51bad4">

**Comment by xzajyjs** [comment]
What is your computer resolution and scaling? I can't reproduce your problem.

**Comment by lolminerxmrig** [comment]
win 10 x 64

![image](https://github.com/xzajyjs/ThunderSearch/assets/108659226/5cdbabb5-62b6-4377-8239-1588c7a04e74)

**Comment by xzajyjs** [comment]
All update in [v2.5.1](https://github.com/xzajyjs/ThunderSearch/releases/tag/v2.5.1).

**Comment by lolminerxmrig** [comment]
thanks 
but only left and right.
up and down not work.

**Comment by lolminerxmrig** [comment]
can add new Edit more 10000 item save.
